# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - worker/*

resources:
  repositories:
    - repository: self

variables:
  dockerRegistryServiceConnection: '55b810f7-0ca8-4cb2-8889-14ab337ed9ba'
  imageRepository: 'workerapp'
  containerRegistry: 'himatejacicd.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/worker/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'azureagent'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'

- stage: Push
  displayName: Push
  dependsOn: Build
  jobs:
  - job: Push
    displayName: Push
    pool:
      name: 'azureagent'
    steps:
    - task: Docker@2
      displayName: Push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

- stage: Update
  displayName: Update Kubernetes Manifests
  dependsOn: Push
  jobs:
  - job: Update
    displayName: Update K8s YAML
    pool:
      name: 'azureagent'
    steps:
    - checkout: self
      persistCredentials: true   # ✅ ensures push works using System.AccessToken

    - script: |
        sudo apt-get update -y
        sudo apt-get install -y dos2unix
        dos2unix scripts/*.sh
      displayName: "Normalize line endings"

    - task: ShellScript@2
      inputs:
        scriptPath: 'scripts/updateK8sManifests.sh'
        args: 'worker $(imageRepository) $(tag)'
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)  # for worker service

